"""Add limit and gtt fields to orders

Revision ID: 091056e6f682
Revises: 59b02576983b
Create Date: 2026-05-01 17:09:33.396813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091056e6f682'
down_revision: Union[str, Sequence[str], None] = '59b02576983b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('limit_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('gtt_sl', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('gtt_target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'gtt_target')
    op.drop_column('orders', 'gtt_sl')
    op.drop_column('orders', 'limit_price')
    op.drop_column('orders', 'order_type')
    # ### end Alembic commands ###
