"""add product_type to orders and positions

Revision ID: 59b02576983b
Revises: e5e88001e755
Create Date: 2026-04-25 21:56:57.343073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b02576983b'
down_revision: Union[str, Sequence[str], None] = 'e5e88001e755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('product_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'product_type')
    op.drop_column('orders', 'product_type')
    # ### end Alembic commands ###
