"""Initial schema

Revision ID: c5f85821f690
Revises: 
Create Date: 2026-04-24 22:52:41.763708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f85821f690'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get the current connection and inspect existing tables
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # 1. Create Users Table (only if missing)
    if 'users' not in existing_tables:
        op.create_table('users',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('username', sa.String(), nullable=True),
            sa.Column('hashed_password', sa.String(), nullable=True),
            sa.Column('balance', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 2. Create Orders Table (only if missing)
    if 'orders' not in existing_tables:
        op.create_table('orders',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('symbol', sa.String(), nullable=True),
            sa.Column('side', sa.String(), nullable=True),
            sa.Column('quantity', sa.Float(), nullable=True),
            sa.Column('price', sa.Float(), nullable=True),
            sa.Column('status', sa.String(), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.Column('owner_id', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
        op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)

    # 3. Create Positions Table (only if missing)
    if 'positions' not in existing_tables:
        op.create_table('positions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('symbol', sa.String(), nullable=True),
            sa.Column('quantity', sa.Float(), nullable=True),
            sa.Column('avg_price', sa.Float(), nullable=True),
            sa.Column('owner_id', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
        op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
