"""Portfolio refactor columns

Revision ID: e5e88001e755
Revises: c5f85821f690
Create Date: 2026-04-24 22:56:04.188633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e88001e755'
down_revision: Union[str, Sequence[str], None] = 'c5f85821f690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # 1. Add new columns safely
    order_cols = [c['name'] for c in inspector.get_columns('orders')]
    if 'profit' not in order_cols:
        op.add_column('orders', sa.Column('profit', sa.Float(), nullable=True))
        
    user_cols = [c['name'] for c in inspector.get_columns('users')]
    if 'cash_balance' not in user_cols:
        op.add_column('users', sa.Column('cash_balance', sa.Float(), nullable=True))
    if 'total_invested_value' not in user_cols:
        op.add_column('users', sa.Column('total_invested_value', sa.Float(), nullable=True))
    if 'realized_pnl' not in user_cols:
        op.add_column('users', sa.Column('realized_pnl', sa.Float(), nullable=True))
    if 'deposited_capital' not in user_cols:
        op.add_column('users', sa.Column('deposited_capital', sa.Float(), nullable=True))
    
    # 2. Data Migration: Preserve existing user balances (only if 'balance' still exists)
    if 'balance' in user_cols:
        op.execute("UPDATE users SET cash_balance = balance, deposited_capital = balance")
    
    # 3. Drop old column safely
    if 'balance' in user_cols:
        with op.batch_alter_table('users') as batch_op:
            batch_op.drop_column('balance')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.FLOAT(), nullable=True))
    op.drop_column('users', 'deposited_capital')
    op.drop_column('users', 'realized_pnl')
    op.drop_column('users', 'total_invested_value')
    op.drop_column('users', 'cash_balance')
    op.drop_column('orders', 'profit')
    # ### end Alembic commands ###
